# After npm install (applies patches for @op-engineering/op-sqlite), run: cd ios && pod install
# Minimum iOS: 12.4 (matches NetrakshAI.xcodeproj). op-sqlite is patched for 12.4 via patch-package.

def patch_text_file(path)
  return unless File.exist?(path)

  original = File.read(path)
  updated = yield(original)
  File.write(path, updated) if updated != original
end

react_native_pods_path = File.expand_path('../node_modules/react-native/scripts/react_native_pods.rb', __dir__)
patch_text_file(react_native_pods_path) do |contents|
  contents = contents.sub("require 'pathname'\n", "require 'pathname'\nrequire 'shellwords'\n") unless contents.include?("require 'shellwords'")
  contents.gsub(
    %q{`sed -i -e  $'s/ && (__IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_10_0)//' #{time_header}`},
    %q{`sed -i -e  $'s/ && (__IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_10_0)//' #{time_header.shellescape}`}
  )
end

script_phases_path = File.expand_path('../node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb', __dir__)
patch_text_file(script_phases_path) do |contents|
  contents
    .gsub(
      '/bin/sh -c "$WITH_ENVIRONMENT $SCRIPT_PHASES_SCRIPT"',
      '"$WITH_ENVIRONMENT" "$SCRIPT_PHASES_SCRIPT"'
    )
    .gsub(
      "ERB.new(template, 0, '->')",
      "ERB.new(template, trim_mode: '->')"
    )
end

with_environment_path = File.expand_path('../node_modules/react-native/scripts/xcode/with-environment.sh', __dir__)
patch_text_file(with_environment_path) do |contents|
  contents.gsub("  $1\n", "  \"$@\"\n")
end

script_phases_shell_path = File.expand_path('../node_modules/react-native/scripts/react_native_pods_utils/script_phases.sh', __dir__)
patch_text_file(script_phases_shell_path) do |contents|
  contents
    .gsub(
      '        JS_SRCS=$(find "$PODS_TARGET_SRCROOT/$SRCS_DIR" -type f -name "$SRCS_PATTERN" -print0 | xargs -0)',
      "        JS_SRCS=()\n        while IFS= read -r -d '' file; do\n            JS_SRCS+=(\"$file\")\n        done < <(find \"$PODS_TARGET_SRCROOT/$SRCS_DIR\" -type f -name \"$SRCS_PATTERN\" -print0)"
    )
    .gsub(
      '        JS_SRCS="$PODS_TARGET_SRCROOT/$SRCS_DIR"',
      '        JS_SRCS=("$PODS_TARGET_SRCROOT/$SRCS_DIR")'
    )
    .gsub(
      "# shellcheck disable=SC2086\n    # $JS_SRCS not having double quotations is intentional\n    \"$NODE_BINARY\" \"$CODEGEN_CLI_PATH/lib/cli/combine/combine-js-to-schema-cli.js\" \"$GENERATED_SCHEMA_FILE\" $JS_SRCS",
      '"$NODE_BINARY" "$CODEGEN_CLI_PATH/lib/cli/combine/combine-js-to-schema-cli.js" "$GENERATED_SCHEMA_FILE" "${JS_SRCS[@]}"'
    )
end

yoga_value_path = File.expand_path('../node_modules/react-native/ReactCommon/yoga/yoga/YGValue.h', __dir__)
patch_text_file(yoga_value_path) do |contents|
  contents
    .gsub('operator"" _pt', 'operator""_pt')
    .gsub('operator"" _percent', 'operator""_percent')
end

boost_podspec_path = File.expand_path('../node_modules/react-native/third-party-podspecs/boost.podspec', __dir__)
patch_text_file(boost_podspec_path) do |contents|
  contents.gsub(
    'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2',
    'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2'
  )
end

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'NetrakshAI' do
  config = use_native_modules!

  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Set iOS 12.4 for all pods to ensure compatibility
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end
  end
end
